"""'abc'

Revision ID: 47fd3534e6d0
Revises: b0efbfd06378
Create Date: 2018-12-25 20:15:25.913757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fd3534e6d0'
down_revision = 'b0efbfd06378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('abc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'abc')
    # ### end Alembic commands ###
