"""'unique'

Revision ID: 6bf9cd5f260a
Revises: 73e28c013481
Create Date: 2018-12-25 20:33:24.394471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bf9cd5f260a'
down_revision = '73e28c013481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['id'])
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('permissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
