# Generated by Django 2.1.4 on 2019-01-02 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=20)),
                ('hgender', models.BooleanField()),
                ('hcontent', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardtitle', models.CharField(max_length=50)),
                ('bpub_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='heroinfo',
            name='hboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.Leaderboard'),
        ),
    ]
