"""'增加admin相关类'

Revision ID: 078bbf858f59
Revises: 
Create Date: 2018-12-29 14:54:40.563637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '078bbf858f59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('passwd', sa.String(length=100), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('AdminLog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('release_time', sa.Date(), nullable=True),
    sa.Column('star', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logo'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('url')
    )
    op.create_table('op_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('option', sa.String(length=50), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('logo', table_name='movies')
    op.drop_index('title', table_name='movies')
    op.drop_index('url', table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('add_time', mysql.DATETIME(), nullable=True),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('info', mysql.TEXT(), nullable=True),
    sa.Column('logo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('area', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('length', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('release_time', sa.DATE(), nullable=True),
    sa.Column('star', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='movies_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('url', 'movies', ['url'], unique=True)
    op.create_index('title', 'movies', ['title'], unique=True)
    op.create_index('logo', 'movies', ['logo'], unique=True)
    op.drop_table('op_log')
    op.drop_table('Movies')
    op.drop_table('AdminLog')
    op.drop_table('admin')
    # ### end Alembic commands ###
